config/routes.rb
Rails.application.routes.draw do
  resources :file_uploads
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'file_uploads#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/file_upload.rb
class FileUpload < ApplicationRecord
  mount_uploaders :attachments, AttachmentUploader

  def save
    super
    rescue ActiveRecord::RecordNotUnique => err
      errors.add :attachments, "'#{attachments.file.original_filename}' already exists"
      false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  before_action :set_file_upload, only: [:edit, :update, :show, :destroy]
  def index
    @file = FileUpload.new
    @files = FileUpload.all
  end

  def new
    @file = FileUpload.new
  end

  def show
  end

  def create
    @file = FileUpload.new(file_params)
    if @file.save
      redirect_to file_uploads_path, notice: "the file has been uploaded"
    else
      @files = FileUpload.all
      render "index"
    end
  end

  def update
  end

  def destroy
    @file = FileUpload.find(params[:id])
    @file.destroy
    redirect_to file_uploads_path, notice: "the file has been deleted"
  end

  private

  def file_params
    params.require(:file_upload).permit({attachments: []})
  end

  def set_file_upload
    @file = FileUpload.find(params[:id])
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/file_uploads/create.html.erb
<h1>FileUploads#create</h1>
<p>Find me in app/views/file_uploads/create.html.erb</p>

app/views/file_uploads/destroy.html.erb
<h1>FileUploads#destroy</h1>
<p>Find me in app/views/file_uploads/destroy.html.erb</p>

app/views/file_uploads/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<% if !@file.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well">
  <%= form_for @file, html: { multipart: true } do |f| %>
    <%= f.label :attachment %>
    <%= f.file_field :attachments, multiple: true %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Download Link</th>
      <th>Thumbnail</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @files.each do |file| %>
      <% file.attachments.each do |attachment| %>
        <tr>
          <td><%= link_to "Download File", attachment.url %></td>
          <td><%= image_tag(attachment.thumb.url.to_s) %></td>
          <td><%= button_to "Delete",  file_upload_path(file), method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete this file?" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/file_uploads/new.html.erb
<% if !@file.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well">
  <%= form_for @file, html: { multipart: true } do |f| %>
    <%= f.label :attachments %>
    <%= f.file_field :attachments, multiple: true  %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Filetransferapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>